// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPSIDS
{
        public const string leaderboard_best_scores = "CgkIk4z_5MIZEAIQDQ"; // <GPGSID>
        public const string achievement_where_no_robot_has_gone_before = "CgkIk4z_5MIZEAIQCw"; // <GPGSID>
        public const string achievement_full_turbo = "CgkIk4z_5MIZEAIQCA"; // <GPGSID>
        public const string achievement_not_boat_yet = "CgkIk4z_5MIZEAIQBg"; // <GPGSID>
        public const string achievement_empty_pockets = "CgkIk4z_5MIZEAIQBQ"; // <GPGSID>
        public const string achievement_lightning = "CgkIk4z_5MIZEAIQBw"; // <GPGSID>
        public const string achievement_jogging = "CgkIk4z_5MIZEAIQAg"; // <GPGSID>
        public const string achievement_time_traveler = "CgkIk4z_5MIZEAIQCg"; // <GPGSID>
        public const string achievement_easy_money = "CgkIk4z_5MIZEAIQDA"; // <GPGSID>
        public const string achievement_pocket_change = "CgkIk4z_5MIZEAIQAQ"; // <GPGSID>
        public const string achievement_greedy = "CgkIk4z_5MIZEAIQAw"; // <GPGSID>
        public const string achievement_show_me_the_coins = "CgkIk4z_5MIZEAIQCQ"; // <GPGSID>
        public const string achievement_run_robot_run = "CgkIk4z_5MIZEAIQBA"; // <GPGSID>

}

